### ISSUE TITLE
Error when added it to PM

### ISSUE THREAD

**Issue by blackhuman** [kean/PulseBeta#1]
After parsing, Xcode says "invalid custom path 'Source/Pulse' for target 'Pulse', it seems the repo lack of some dir and files, comparing to the PulseUI repo.
![image](https://user-images.githubusercontent.com/2269615/113950067-122b7200-9843-11eb-904e-d6199b9a0b5e.png)

**Comment by kean** [comment]
Fixed, thanks for reporting https://github.com/kean/PulseBeta/releases/tag/0.14.2. My bad, forgot to add it.
